FROM node:latest

WORKDIR /usr/src/app

COPY --chown=node:node ./frontend/package.json	./
COPY --chown=node:node ./frontend/tsconfig.json	./

RUN yarn install

VOLUME [ "/usr/src/app/src" ]
VOLUME [ "/usr/src/app/public" ]

COPY --chown=node:node ./shared ./shared

EXPOSE 80

CMD npm start
