FROM node:latest

WORKDIR /usr/src/app/frontend

COPY --chown=node:node ./frontend/package.json	./
COPY --chown=node:node ./frontend/tsconfig.json	./

RUN yarn install

VOLUME [ "/usr/src/app/frontend/src" ]
VOLUME [ "/usr/src/app/frontend/public" ]
VOLUME [ "/usr/src/app/shared" ]

EXPOSE 80

CMD npm start
