version: '3.9'


networks:
  back:
    name: backend
  front:
    name: frontend
#    enable_ipv6: true



services:
  postgres:
    # names
    container_name: postgres
    domainname: postgres
    hostname: postgres
    # build
    image: postgres:latest
    env_file:
      - .env
    # runtime
    expose:
      - "5432"
    restart: always
    networks:
      - back


  nestjs:
    # names
    container_name: nestjs
    domainname: nestjs
    hostname: nestjs
    # build
    build:
      context: ./backend
      dockerfile: Dockerfile
    #runtime
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PORT=${PORT}
      - PORT_SERVER=${PORT_SERVER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TTL=${JWT_TTL}
      - API_UID=${API_UID}
      - API_SECRET=${API_SECRET}
    depends_on:
      - postgres
    expose:
      - "3000"
    ports:
      - 3000:3000
    restart: always
    networks:
      - back
      - front
    volumes:
      - ./backend/src:/usr/src/app/src


  web:
    # names
    container_name: web
    domainname: web
    hostname: web
    # build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #runtime
    environment:
      - PORT=${PORT}
      - API_UID=${API_UID}
    depends_on:
      - nestjs
    ports:
      - ${PORT}:${PORT}
    restart: always
    networks:
      - front
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "80:80"
    networks:
      - back
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      DEBUG: 'False'
